version: "3.9"
services:
  image-processing:
    image: localhost:5000/image-processing
    build: ./image-processing
    container_name: image-processing
    restart: always
    ports:
      - "8080:80"
    environment:
      - SERVER_PORT=80
      - BLOB-STORE_HOST=blob-store
      - BLOB-STORE_PORT=80
      - WORKER-SERVICE_HOST=worker-service
      - WORKER-SERVICE_PORT=80
  worker-service:
    build: ./worker-service
    image: localhost:5000/worker-service
    container_name: worker-service
    restart: always
    ports:
      - "8081:80"
    environment:
      - SERVER_PORT=80

  blob-store:
    build: ./blob-store
    image: localhost:5000/blob-store
    container_name: blob-store
    restart: always
    ports:
      - "8082:80"
    environment:
      - BLOB_LOCATION=/images
      - SERVER_PORT=80
